const PLAYER_LIVES = 3;
const PLAYER_SPEED = 600;
const JUMP_HEIGHT = 1400;
const NUMBER_OF_PLATFORMS_AT_START = 15;
const MAX_NUMBER_OF_PLATFORMS = 320;
const TIME_SECONDS = 90;
const FREQUENCY_OF_GOATS = 15;
const PERCENT_CHANCE_APPEAR_POWERUP = 10;
